--Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

--1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

--Find the sum of all the even-valued terms in the sequence which do not exceed four million.


fibs = 1 : 2 : [ a + b | (a, b) <- zip fibs (tail fibs)]
sol2 = sum [x | x <- fibs, x `mod` 2 == 0 && x < 4000001]
