{-
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
-}


fibs = 1 : 2 : [ a + b | (a, b) <- zip fibs (tail fibs)]
fibs2 = [x | x<- takeWhile (<=4000000) fibs, even x]
sol2 = sum fibs2
--sol2 = sum [x | x<- takeWhile (<=4000000) fibs, even x]
